version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/b-map:/var/www
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src/b-map:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db-host
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: bmap_db
        MYSQL_ROOT_PASSWORD: lohn0922
        MYSQL_USER: kensukesann
        MYSQL_PASSWORD: airchair1997
        TZ: 'Asia/Tokyo'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8888:80
    depends_on:
      - db



